### ISSUE TITLE
Global Dict doesn't work when load blend in game

### ISSUE THREAD

**Issue by lordloki** [UPBGE/blender#864]
Several reports in blenderartists point out that the Global Dict gets clear out when a blend is loaded in a game.

I need to test it.

**Comment by panzergame** [comment]
The global dict isn't cleared when loading an other file, and that was a feature to keep something global to the game.

**Comment by Cotaks** [comment]
indeed, it does not really get cleared, but it does not set them as well, strange things happening with GD, i was so happy that loki fixed the Libload, but now GD and mouse center is the bottleneck, before i and more of us can hop over to upBge.

**Comment by panzergame** [comment]
Sorry, what do you mean by strange things happening ?

If you can reproduce a bug related to the global dict, could you provide an example file so that we can test and fix ?

Thanks in advance.

**Comment by Cotaks** [comment]
Hmm, strange things, if i load my project, 90% stops working, seems like key events like just_activated does not work anymore, key presses wont register animation wont work. But if i load in my movement script alone it works, but in my project (same code) does not work. Key binds the same thing, if i set it in my project i get empty keys, if i open just the movement script all is fine.

**Comment by panzergame** [comment]
@Cotaks : Look at recent builds: https://download.upbge.org/download/release/windows64/UPBGE_master_v0.2.4d20181007h0513b96Windows64.zip
https://download.upbge.org/download/release/linux64/UPBGE_master_v0.2.4b2.79d20181007h0513b96Linux64.tar.xz

**Comment by Cotaks** [comment]
@panzergame already tried that build, same issues

**Comment by panzergame** [comment]
`activeInputs` hold `SCA_InputEvent`(https://pythonapi.upbge.org/bge.types.SCA_InputEvent.html) all the test doing `input == integer` are now wrong. You should replace them by `input.activated`.

By doing this on the file keybindings.py i was able to jump and display the menu.

**Comment by Cotaks** [comment]
@panzergame Ok for the jumping part it succeeded, the menu should always work, a brick is used for this.

But other then that i can get 1 more key to work (half).
i changed from == 1 to .activated, oh boy half the stuff breaks, blender crashes over and over, getting this error:

Error: Python(player), Python script error
Traceback (most recent call last):
  File "D:\_blender\_upbge projects\libload_werkend_upbge.blend\player.py", line 134, in movement
  File "D:\_blender\_upbge projects\libload_werkend_upbge.blend\player.py", line 163, in run_more_scripts
  File "D:\_blender\_upbge projects\libload_werkend_upbge.blend\player.py", line 296, in skills
AttributeError: 'int' object has no attribute 'activated'

ok fine why are you an int object now? So i changed it back to ==1, hehe not working at all.
So back to .activated, hey key 1 works, but 2/leftclick/e/r/etc keys are doing nothing and that error is the only one i have.

**Comment by panzergame** [comment]
If the object is int it means that your are still using `events` instead of `inputs`.

**Comment by Cotaks** [comment]
only using this line 'keycode         = events.__dict__[key_event]' to get the keycode. everything else is keyboard.inputs, and it works, but just crashing blender on half the keys 

walking is working, skills instantly crashing blender, error is still there.
I have packed everything here: https://files.fm/u/vxgnjtjh
(scripts are opened at the right spots).

**Comment by panzergame** [comment]
In the test file you provided, your function `button_status` can return None. But you didn't check this value. It's seems to happen when the scene isn't libloaded, maybe you load the binding after ?

Anyway excepted this python error at startup, every is working fine for me. I can walk jump in the castle.

**Comment by Cotaks** [comment]
>  every is working fine for me. I can walk jump in the castle.
And upbge don't crash if you press 1 or 2 key?

**Comment by panzergame** [comment]
Yes, it is not crashing. I advise you to test tonight or tomorrow with the next build.

**Comment by panzergame** [comment]
@Cotaks : Can you confirm that it's working ?

**Comment by Cotaks** [comment]
@panzergame Can't confirm yet, sorry had some family drama so didn't have much time to test the new build yet, will see if i can do it tonight.

**Comment by Cotaks** [comment]
@panzergame

A video, funny thing 3rd time it actually showed the weapon, but cut down my fps to 12 and crashed, 4th time it tried but crashed, just like all the other tries.

https://youtu.be/6Dr6tjPEnwY

**Comment by lordloki** [comment]
In debug mode the game load bad. Here it is the crash when press 1 and make several shots.
![image](https://user-images.githubusercontent.com/1015605/47265487-e0b27500-d528-11e8-85ae-7500bb625810.png)

Additionally, in the console windows we have a warning between static-static collision
![image](https://user-images.githubusercontent.com/1015605/47265497-093a6f00-d529-11e8-8420-f9891c369966.png)

**Comment by lordloki** [comment]
Tested with last master and bug is fixed!!!
Good work @panzergame

**Comment by Cotaks** [comment]
@panzergame 
@lordloki 

I don't want to make this thread more offtopic, but a few things to add.

1)
> "This is what i see when i press P:"

That screenshot is because Libload loads, when it's ready loading it goes to next_frame, then the player position is set. But somehow the position gets set before the blend files are actually loaded in, resulting in player gets spawned (no world yet), player falling.....world loads in....player is already below the ground and keeps falling.

So something is not right yet (normal blender does not have this issue)

2)
Indeed Thanks for fixing the crash, but....

Now when i press in my frame rate gets down to +- 30, just by pressing 1. (in bge itself it runs smooth at 60+ frames)

3)
The error mentioned earlier? 
https://github.com/UPBGE/blender/issues/864#issuecomment-428583419

I Had another go at it, and it seems not to be my fault, something is not good with returning the inputs events. Most things works but this error keeps spitting out. screenshot will explain a lot more.

![key and mouse events problem](https://user-images.githubusercontent.com/41304048/49768326-44ad1a80-fcdc-11e8-825c-7e1df11a5aa2.png)

**Comment by warcaninos** [comment]
Seem like this issue can be closed
